### ISSUE TITLE
Link child to ancestor if parent types are not on the diagram

### ISSUE THREAD

**Issue by Kaon68** [realvizu/softvis#10]
In the actual version, you see the inheritance hierarchy only if all types are on the diagram. If a type is missing on the diagram, the hierarchical tree is split in two as separated objects.

Suggestion : link related (as ancestor/child) types with a specific link type (providing some actions to see how many types there is between the two types, reinsert them on the diagram, etc.)

Like : 
A <- B <- C <- D
A <****** D

**Comment by realvizu** [comment]
Thanks for the suggestion, sounds like a useful feature, I'll put it on the roadmap.
I'm a bit concerned about the performance implications as it will require lots of path searching in the model graph but we'll see whether that's a real issue or not.

**Comment by realvizu** [comment]
Closing this issue because this repo is going to be archived.
The successor of this tool is called Codartis Diagram Tool and is not OSS any more.
You can find it at: https://codartis.com
