### ISSUE TITLE
VS2017 support

### ISSUE THREAD

**Issue by realvizu** [realvizu/softvis#11]

**Comment by ManfredLange** [comment]
Although one source code commit appears to have a comment suggesting VS2017 is target by the vsix, running the installer fails with an error for "Visual Studio Professional 2017 Version 15.1 (26403.3) Release"

**Comment by realvizu** [comment]
VS2017 support is under development. I've ran into difficulties when trying to target both VS2015 and VS2017. I'm trying to sort it out...

**Comment by realvizu** [comment]
Here's a build that works with VS2015 and VS2017.
https://ci.appveyor.com/api/buildjobs/psqko832d76y3yca/artifacts/source%2FSoftVis.VisualStudioIntegration.Vs2017%2Fbin%2FRelease%2FQuickDiagramTool.vsix

Not well tested yet but you can give it a try.
