### ISSUE TITLE
Add fields, properties and methods to diagram

### ISSUE THREAD

**Issue by mhanysz** [realvizu/softvis#15]
It would be a very handy enhancement, if one could show the methods, fields and properties of a class in the quick diagram. It is already possible to show the description of the class, so replacing this text with the list of methods, fields and properties when the user clicks a "Show/Hide Details" button may be rather straight forward. This would make the quick diagram a UML class diagram that can be used to generate code documentation if needed.

**Comment by realvizu** [comment]
Actually a similar but more complex feature is in the works: showing type members (methods, fields, properties) as model elements (not as simple text) so you can selectively show/hide them and also show relationships between them (like which method calls which other methods). But it's a substantial work and lately I didn't have much time for this pet projects as my day-job keeps me busy.

So thanks for the suggestion, I'll think about implementing it the way you proposed it (showing members as text) as a temporary solution until my more ambitious feature gets done.

**Comment by joelmnz** [comment]
@realvizu  This sounds exactly like what I need, do you have a branch with WorkInProgress that I could carry on from?

**Comment by realvizu** [comment]
Closing this issue because this repo is going to be archived.
The successor of this tool is called Codartis Diagram Tool and is not OSS any more.
You can find it at: https://codartis.com
