### ISSUE TITLE
How to Uninstall

### ISSUE THREAD

**Issue by PGPatrudu** [realvizu/softvis#16]
Hi,
       Please explain how to Uninstall this product, in the documentation.
       I dont see it in control panel (Windows).
Thanks & Regards
Pilla Gurumurty Patrudu

**Comment by realvizu** [comment]
This is a Visual Studio Extension, not a standalone product, so you uninstall it from Visual Studio.
Tools menu > Extensions and Updates > find it in the installed extensions list and click the Uninstall button.
