### ISSUE TITLE
VS2019 Version

### ISSUE THREAD

**Issue by Teknel** [realvizu/softvis#17]
What expectation about VS2019 version of this exceptional and intuitive tool?
Thanks

**Comment by realvizu** [comment]
I marked it for the next release but unfortunately I cannot make any predictions when will it come because nowadays I don't have much time for this project. Sorry.

**Comment by Teknel** [comment]
Thanks to answer and congratulations again for this useful toll.

 


-------------------------------------------
José María Cuchian
Teknel Research

Beruti 4441 5to Of"45"
Te: +54 (11) 4772-4230 
Buenos Aires (C1425BDA) - ARGENTINA

 

De: Ferenc Vizkeleti <notifications@github.com> 
Enviado el: Tuesday, March 12, 2019 4:35 PM
Para: realvizu/QuickDiagram <QuickDiagram@noreply.github.com>
CC: Jose Maria Cuchian <jmcuchian@teknel.com.ar>; Author <author@noreply.github.com>
Asunto: Re: [realvizu/QuickDiagram] VS2019 Version (#17)

 

I marked it for the next release but unfortunately I cannot make any predictions when will it come because nowadays I don't have much time for this project. Sorry.

**Comment by realvizu** [comment]
If anyone would like to help here's what to do:
* Branch from this commit: https://github.com/realvizu/QuickDiagram/commit/8220c80a6423d59d0ec32f38a1a4dd9d3d68653e
* Convert the Package to AsyncPackage. This blog post might help: https://github.com/microsoft/VSSDK-Extensibility-Samples/tree/master/AsyncPackageMigration
* Understand and fix all issues reported by the new VS SDK analyzers.
* Test the extension.

**Comment by realvizu** [comment]
Released v0.5.63 to [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=FerencVizkeleti.QuickDiagramToolforC)

Developed on [vs2019](https://github.com/realvizu/QuickDiagram/tree/vs2019) branch.
Package converted to AsyncPackage, csprojs updated to new project format.
Hacked around a problem that VS2015 lacks the async APIs for ToolWindow initialization which led to deadlocking the UI thread.
