### ISSUE TITLE
Selection off-by-three when going to sealed type

### ISSUE THREAD

**Issue by tamlin-mike** [realvizu/softvis#19]
It seems that every time I have displayed a class hierarchy and double-click a `sealed` class to open it in VS, the selection is always off by 3 chars.

Instead of the expected (using '|' as selection markers)
`<tab>public sealed class |TypeName| : BaseName`
it becomes
`<tab>public sealed cla|ss TypeN|ame : BaseName`

I have only seen it on `sealed`, but other keywords could possibly also be affected.

**Comment by realvizu** [comment]
Closing this issue because this repo is going to be archived.
The successor of this tool is called Codartis Diagram Tool and is not OSS any more.
You can find it at: https://codartis.com
