### ISSUE TITLE
QuickDiagram cannot identify Implementing and Derived Types 

### ISSUE THREAD

**Issue by LogicRising** [realvizu/softvis#22]
In a large C# project in VS2019, sometimes QuickDiagram tool is able to locate implementing and derived types, but most of the time it doesn't find any at all.
![image](https://user-images.githubusercontent.com/51454788/146419635-dd0fc689-c563-4ae7-bea0-32963ff88395.png)

It makes no difference whether the class/interface is added to the diagram from its definition in source code, or from one of its references as illustrated above. Cleaning and rebuilding the solution does not make a difference. Restarting Visual Studio and reloading the solution do not solve it either. Manually locating and adding a derived/implemented type to the diagram will usually cause the QuickDiagram tool to discover their relationship, but additional derived/implemented types will remain missing, even if they are present within in the same csproj. I get the feeling it might have something to do with multiple classes/interfaces specified in the same source files but I can't say this with any certainty.

This is frustrating because it makes this extension almost useless.

**Comment by realvizu** [comment]
Sorry but this repo is not actively maintained so this bug may never be fixed.
There are many flaws in this implementation that cannot be easily fixed but requires a complete rethinking and rewrite.
I'm working on a new (rewritten) version i'm hoping to release in 2022 but it won't be free any more. I'll post about it when it will be available.

**Comment by realvizu** [comment]
Closing this issue because this repo is going to be archived.
The successor of this tool is called Codartis Diagram Tool and is not OSS any more.
You can find it at: https://codartis.com
